### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [HMC-ACE/muddUltrasound#1]
Hello!

I found this project from https://hackaday.com/2023/03/08/supercon-2022-alec-vercruysse-can-see-through-murky-water/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by AlecVercruysse** [comment]
Hello, thank you for raising this issue! We've added an MIT license.

**Comment by vazhnov** [comment]
The MIT license — great! Thank you!
