### ISSUE TITLE
helpful !

### ISSUE THREAD

**Issue by 1kaiser** [HMC-ACE/muddUltrasound#2]
1. https://www.youtube.com/watch?v=vAEZvYlUnEM
2. https://www.youtube.com/watch?v=z4uxC7ISd-c
3. https://www.youtube.com/watch?v=Evao3XUUAOY
4. https://www.youtube.com/watch?v=h6321UBATps
5. https://www.youtube.com/watch?v=njDQKdZzGMI   <<< can his be used as replacement ?? if this is used in array or mesh mode

**Comment by AlecVercruysse** [comment]
Thank you for the resources! We haven't tested any other transducer element yet, but theoretically, other piezo transducers should work at well. Note that different elements have different resonant frequencies, however (for example, the JSN-SR04T-2.0 is resonant at 40kHz, but our current piezos are resonant at 92kHz). The transmit circuitry, MCU firmware, and beamforming source code would need to be modified to transition to elements of another frequency. Most likely, you'd want to change the spacing of the array as well.
